name: toko_emas_digital
description: Aplikasi Toko Emas Digital - Flutter App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Firebase
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.3
  firebase_messaging: ^16.4.0
  
  # Google Sign In
  google_sign_in: ^6.3.0
  
  # Supabase
  # State Management
  provider: ^6.1.1
  
  # HTTP Client untuk API
  http: ^1.2.0
  
  # URL Launcher
  url_launcher: ^6.2.6
  
  # Image Picker
  image_picker: ^1.0.7
  
  # Shared Preferences
  shared_preferences: ^2.2.2
  
  # Intl untuk format tanggal dan currency
  intl: ^0.20.2
  
  # UUID Generator
  uuid: ^4.3.3
  
  # Google Fonts untuk tipografi premium (Kompatibel dengan Flutter 3.16.x)
  google_fonts: ^8.1.0
  dio: ^5.9.2
  cloud_firestore: ^6.6.0
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
